name: OFA-Tech CI/CD

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch
  workflow_dispatch:

jobs:
  pipeline:
    permissions:
      contents: write
      packages: write
    uses: OFA-Tech/.github/.github/workflows/ci-cd.yml@main
    with:
      gh-runner: self-hosted
      language: node
      language-version: "20"
      language-distribution: ""
      working-directory: "."
      build-command: ""

      run-unit-tests: true
      unit-test-command: ""
      run-integration-tests: false
      integration-test-command: ""

      run-sonar: false
      sonar-enforce-quality-gate: false
      sonar-exclusions: ""

      generate-docker-image: true
      docker-registry: docker.io
      docker-image-namespace: ""
      docker-image-repository: ""
      docker-image-tag: ""
      docker-image-environment: "production"
      dockerfile-path: Dockerfile

      run-deploy: false
      portainer-endpoint-id: ""
      portainer-swarm-id: ""
      portainer-stack-type: swarm
      portainer-stack-name: ""
      portainer-stack-file-content: ""
      portainer-stack-file-path: ""

      run-post-deploy-tests: true
      run-health-check: true
      health-check-url: ""
      health-check-retries: "10"
      rollback-to: ""
    secrets: inherit