name: Sonar Template

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      language-version:
        required: false
        type: string
        default: ""
      distribution:
        required: false
        type: string
        default: ""
      runner:
        required: false
        type: string
        default: ubuntu-latest
      working-directory:
        required: false
        type: string
        default: .
      sonar-project-key:
        required: false
        type: string
        default: ""
      sonar-project-name:
        required: false
        type: string
        default: ""
      sonar-sources:
        required: false
        type: string
        default: .
      sonar-command:
        required: false
        type: string
        default: ""
      enforce-quality-gate:
        required: false
        type: boolean
        default: false
      sonar-token:
        required: false
        type: string
        default: ""
      sonar-host-url:
        required: false
        type: string
        default: ""

jobs:
  sonar:
    uses: ./.github/workflows/stage-sonar.yml
    with:
      language: ${{ inputs.language }}
      language-version: ${{ inputs.language-version }}
      distribution: ${{ inputs.distribution }}
      runner: ${{ inputs.runner }}
      working-directory: ${{ inputs.working-directory }}
      sonar-project-key: ${{ inputs.sonar-project-key }}
      sonar-project-name: ${{ inputs.sonar-project-name }}
      sonar-sources: ${{ inputs.sonar-sources }}
      sonar-command: ${{ inputs.sonar-command }}
      enforce-quality-gate: ${{ inputs.enforce-quality-gate }}
      sonar-token: ${{ inputs.sonar-token }}
      sonar-host-url: ${{ inputs.sonar-host-url }}
